<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Petshop.Petshop.MVC\**" />
    <Content Remove="Petshop.Petshop.MVC\**" />
    <EmbeddedResource Remove="Petshop.Petshop.MVC\**" />
    <None Remove="Petshop.Petshop.MVC\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-grid.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-grid.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-grid.min.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-grid.min.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-grid.rtl.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-grid.rtl.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-grid.rtl.min.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-grid.rtl.min.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-reboot.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-reboot.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-reboot.min.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-reboot.min.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-reboot.rtl.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-reboot.rtl.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-reboot.rtl.min.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-reboot.rtl.min.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-utilities.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-utilities.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-utilities.min.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-utilities.min.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-utilities.rtl.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-utilities.rtl.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-utilities.rtl.min.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap-utilities.rtl.min.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap.min.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap.min.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap.rtl.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap.rtl.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap.rtl.min.css" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\css\bootstrap.rtl.min.css.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\js\bootstrap.bundle.js" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\js\bootstrap.bundle.js.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\js\bootstrap.bundle.min.js" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\js\bootstrap.bundle.min.js.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\js\bootstrap.esm.js" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\js\bootstrap.esm.js.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\js\bootstrap.esm.min.js" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\js\bootstrap.esm.min.js.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\js\bootstrap.js" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\js\bootstrap.js.map" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\js\bootstrap.min.js" />
    <Content Remove="C:\Users\Karolina\.nuget\packages\bootstrap\5.3.8\contentFiles\any\any\wwwroot\js\bootstrap.min.js.map" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Petshop.MVC\Views\Shared\_Layout.cshtml.css" />
    <None Remove="Petshop.MVC\Views\_Layout.cshtml.css" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Petshop.MVC\Views\Shared\_Layout.cshtml.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Petshop.MVC\wwwroot\css\site.css" />
    <Content Include="Petshop.MVC\wwwroot\favicon.ico" />
    <Content Include="Petshop.MVC\wwwroot\js\site.js" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery-validation-unobtrusive\dist\jquery.validate.unobtrusive.js" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery-validation-unobtrusive\dist\jquery.validate.unobtrusive.min.js" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery-validation-unobtrusive\LICENSE.txt" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery-validation\dist\additional-methods.js" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery-validation\dist\additional-methods.min.js" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery-validation\dist\jquery.validate.js" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery-validation\dist\jquery.validate.min.js" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery-validation\LICENSE.md" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery\dist\jquery.js" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery\dist\jquery.min.js" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery\dist\jquery.min.map" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery\dist\jquery.slim.js" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery\dist\jquery.slim.min.js" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery\dist\jquery.slim.min.map" />
    <Content Include="Petshop.MVC\wwwroot\lib\jquery\LICENSE.txt" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="lib\" />
    <Folder Include="Petshop.BLL\Interfaces\" />
    <Folder Include="Petshop.BLL\Services\" />
    <Folder Include="Petshop.DAL\Migrations\" />
    <Folder Include="Petshop.DAL\Models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="bootstrap" Version="5.3.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Content Update="Petshop.MVC\Views\Shared\_Layout.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
