// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Petshop.DAL;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(PetshopDBcontext))]
    [Migration("20260918223500_AddProducts")]
    partial class AddProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Petshop.DAL.Models.Category", b =>
                {
                    b.Property<int>("Kategorija_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Kategorija_id"));

                    b.Property<string>("nazivkategorije")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Kategorija_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WebApplication1.Petshop.DAL.Models.Order", b =>
                {
                    b.Property<int>("porudzbina_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("porudzbina_id"));

                    b.Property<DateTime>("Datumporudzbine")
                        .HasColumnType("datetime2");

                    b.Property<int>("korisnik_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ukupnacena")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("porudzbina_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebApplication1.Petshop.DAL.Models.Orderitems", b =>
                {
                    b.Property<int>("stavkaporudzbine_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stavkaporudzbine_id"));

                    b.Property<int>("Proizvod_id")
                        .HasColumnType("int");

                    b.Property<decimal>("cena")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("kolicina")
                        .HasColumnType("int");

                    b.Property<int>("porudzbina_id")
                        .HasColumnType("int");

                    b.HasKey("stavkaporudzbine_id");

                    b.ToTable("Orderitems");
                });

            modelBuilder.Entity("WebApplication1.Petshop.DAL.Models.Product", b =>
                {
                    b.Property<int>("Proizvod_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Proizvod_id"));

                    b.Property<decimal>("cena")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("kategorija_id")
                        .HasColumnType("int");

                    b.Property<int>("kolicinanastanju")
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Proizvod_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebApplication1.Petshop.DAL.Models.User", b =>
                {
                    b.Property<int>("Korsnik_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Korsnik_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Korsnik_id"));

                    b.Property<string>("adresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("adresa");

                    b.Property<int>("br_telefona")
                        .HasColumnType("int")
                        .HasColumnName("br_telefona");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ime");

                    b.Property<string>("lozinka")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lozinka");

                    b.Property<string>("prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("prezime");

                    b.HasKey("Korsnik_id");

                    b.ToTable("korisnik");
                });
#pragma warning restore 612, 618
        }
    }
}
